// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Packet_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Packet_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Packet_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Packet_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Packet_2eproto;
namespace HProtocol {
class Chat;
struct ChatDefaultTypeInternal;
extern ChatDefaultTypeInternal _Chat_default_instance_;
class MatchPlayer;
struct MatchPlayerDefaultTypeInternal;
extern MatchPlayerDefaultTypeInternal _MatchPlayer_default_instance_;
class MatchStart;
struct MatchStartDefaultTypeInternal;
extern MatchStartDefaultTypeInternal _MatchStart_default_instance_;
}  // namespace HProtocol
PROTOBUF_NAMESPACE_OPEN
template<> ::HProtocol::Chat* Arena::CreateMaybeMessage<::HProtocol::Chat>(Arena*);
template<> ::HProtocol::MatchPlayer* Arena::CreateMaybeMessage<::HProtocol::MatchPlayer>(Arena*);
template<> ::HProtocol::MatchStart* Arena::CreateMaybeMessage<::HProtocol::MatchStart>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace HProtocol {

// ===================================================================

class Chat final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:HProtocol.Chat) */ {
 public:
  inline Chat() : Chat(nullptr) {}
  ~Chat() override;
  explicit PROTOBUF_CONSTEXPR Chat(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Chat(const Chat& from);
  Chat(Chat&& from) noexcept
    : Chat() {
    *this = ::std::move(from);
  }

  inline Chat& operator=(const Chat& from) {
    CopyFrom(from);
    return *this;
  }
  inline Chat& operator=(Chat&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Chat& default_instance() {
    return *internal_default_instance();
  }
  static inline const Chat* internal_default_instance() {
    return reinterpret_cast<const Chat*>(
               &_Chat_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Chat& a, Chat& b) {
    a.Swap(&b);
  }
  inline void Swap(Chat* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Chat* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Chat* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Chat>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Chat& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Chat& from) {
    Chat::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Chat* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HProtocol.Chat";
  }
  protected:
  explicit Chat(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgFieldNumber = 1,
  };
  // string msg = 1;
  void clear_msg();
  const std::string& msg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_msg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_msg();
  PROTOBUF_NODISCARD std::string* release_msg();
  void set_allocated_msg(std::string* msg);
  private:
  const std::string& _internal_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_msg(const std::string& value);
  std::string* _internal_mutable_msg();
  public:

  // @@protoc_insertion_point(class_scope:HProtocol.Chat)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Packet_2eproto;
};
// -------------------------------------------------------------------

class MatchPlayer final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:HProtocol.MatchPlayer) */ {
 public:
  inline MatchPlayer() : MatchPlayer(nullptr) {}
  ~MatchPlayer() override;
  explicit PROTOBUF_CONSTEXPR MatchPlayer(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MatchPlayer(const MatchPlayer& from);
  MatchPlayer(MatchPlayer&& from) noexcept
    : MatchPlayer() {
    *this = ::std::move(from);
  }

  inline MatchPlayer& operator=(const MatchPlayer& from) {
    CopyFrom(from);
    return *this;
  }
  inline MatchPlayer& operator=(MatchPlayer&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MatchPlayer& default_instance() {
    return *internal_default_instance();
  }
  static inline const MatchPlayer* internal_default_instance() {
    return reinterpret_cast<const MatchPlayer*>(
               &_MatchPlayer_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(MatchPlayer& a, MatchPlayer& b) {
    a.Swap(&b);
  }
  inline void Swap(MatchPlayer* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MatchPlayer* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MatchPlayer* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MatchPlayer>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MatchPlayer& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MatchPlayer& from) {
    MatchPlayer::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MatchPlayer* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HProtocol.MatchPlayer";
  }
  protected:
  explicit MatchPlayer(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerCharacterFieldNumber = 1,
  };
  // uint32 playerCharacter = 1;
  void clear_playercharacter();
  uint32_t playercharacter() const;
  void set_playercharacter(uint32_t value);
  private:
  uint32_t _internal_playercharacter() const;
  void _internal_set_playercharacter(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:HProtocol.MatchPlayer)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t playercharacter_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Packet_2eproto;
};
// -------------------------------------------------------------------

class MatchStart final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:HProtocol.MatchStart) */ {
 public:
  inline MatchStart() : MatchStart(nullptr) {}
  ~MatchStart() override;
  explicit PROTOBUF_CONSTEXPR MatchStart(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MatchStart(const MatchStart& from);
  MatchStart(MatchStart&& from) noexcept
    : MatchStart() {
    *this = ::std::move(from);
  }

  inline MatchStart& operator=(const MatchStart& from) {
    CopyFrom(from);
    return *this;
  }
  inline MatchStart& operator=(MatchStart&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MatchStart& default_instance() {
    return *internal_default_instance();
  }
  static inline const MatchStart* internal_default_instance() {
    return reinterpret_cast<const MatchStart*>(
               &_MatchStart_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(MatchStart& a, MatchStart& b) {
    a.Swap(&b);
  }
  inline void Swap(MatchStart* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MatchStart* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MatchStart* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MatchStart>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MatchStart& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MatchStart& from) {
    MatchStart::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MatchStart* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HProtocol.MatchStart";
  }
  protected:
  explicit MatchStart(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSurvivorIPFieldNumber = 5,
    kSurvivorCharacterFieldNumber = 6,
    kKillerIPFieldNumber = 3,
    kMaxPlayerFieldNumber = 2,
    kKillerCharacterFieldNumber = 4,
  };
  // repeated string survivorIP = 5;
  int survivorip_size() const;
  private:
  int _internal_survivorip_size() const;
  public:
  void clear_survivorip();
  const std::string& survivorip(int index) const;
  std::string* mutable_survivorip(int index);
  void set_survivorip(int index, const std::string& value);
  void set_survivorip(int index, std::string&& value);
  void set_survivorip(int index, const char* value);
  void set_survivorip(int index, const char* value, size_t size);
  std::string* add_survivorip();
  void add_survivorip(const std::string& value);
  void add_survivorip(std::string&& value);
  void add_survivorip(const char* value);
  void add_survivorip(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& survivorip() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_survivorip();
  private:
  const std::string& _internal_survivorip(int index) const;
  std::string* _internal_add_survivorip();
  public:

  // repeated uint32 survivorCharacter = 6;
  int survivorcharacter_size() const;
  private:
  int _internal_survivorcharacter_size() const;
  public:
  void clear_survivorcharacter();
  private:
  uint32_t _internal_survivorcharacter(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      _internal_survivorcharacter() const;
  void _internal_add_survivorcharacter(uint32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      _internal_mutable_survivorcharacter();
  public:
  uint32_t survivorcharacter(int index) const;
  void set_survivorcharacter(int index, uint32_t value);
  void add_survivorcharacter(uint32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      survivorcharacter() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      mutable_survivorcharacter();

  // string killerIP = 3;
  void clear_killerip();
  const std::string& killerip() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_killerip(ArgT0&& arg0, ArgT... args);
  std::string* mutable_killerip();
  PROTOBUF_NODISCARD std::string* release_killerip();
  void set_allocated_killerip(std::string* killerip);
  private:
  const std::string& _internal_killerip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_killerip(const std::string& value);
  std::string* _internal_mutable_killerip();
  public:

  // uint32 maxPlayer = 2;
  void clear_maxplayer();
  uint32_t maxplayer() const;
  void set_maxplayer(uint32_t value);
  private:
  uint32_t _internal_maxplayer() const;
  void _internal_set_maxplayer(uint32_t value);
  public:

  // uint32 killerCharacter = 4;
  void clear_killercharacter();
  uint32_t killercharacter() const;
  void set_killercharacter(uint32_t value);
  private:
  uint32_t _internal_killercharacter() const;
  void _internal_set_killercharacter(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:HProtocol.MatchStart)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> survivorip_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t > survivorcharacter_;
    mutable std::atomic<int> _survivorcharacter_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr killerip_;
    uint32_t maxplayer_;
    uint32_t killercharacter_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Packet_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Chat

// string msg = 1;
inline void Chat::clear_msg() {
  _impl_.msg_.ClearToEmpty();
}
inline const std::string& Chat::msg() const {
  // @@protoc_insertion_point(field_get:HProtocol.Chat.msg)
  return _internal_msg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Chat::set_msg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.msg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:HProtocol.Chat.msg)
}
inline std::string* Chat::mutable_msg() {
  std::string* _s = _internal_mutable_msg();
  // @@protoc_insertion_point(field_mutable:HProtocol.Chat.msg)
  return _s;
}
inline const std::string& Chat::_internal_msg() const {
  return _impl_.msg_.Get();
}
inline void Chat::_internal_set_msg(const std::string& value) {
  
  _impl_.msg_.Set(value, GetArenaForAllocation());
}
inline std::string* Chat::_internal_mutable_msg() {
  
  return _impl_.msg_.Mutable(GetArenaForAllocation());
}
inline std::string* Chat::release_msg() {
  // @@protoc_insertion_point(field_release:HProtocol.Chat.msg)
  return _impl_.msg_.Release();
}
inline void Chat::set_allocated_msg(std::string* msg) {
  if (msg != nullptr) {
    
  } else {
    
  }
  _impl_.msg_.SetAllocated(msg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.msg_.IsDefault()) {
    _impl_.msg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:HProtocol.Chat.msg)
}

// -------------------------------------------------------------------

// MatchPlayer

// uint32 playerCharacter = 1;
inline void MatchPlayer::clear_playercharacter() {
  _impl_.playercharacter_ = 0u;
}
inline uint32_t MatchPlayer::_internal_playercharacter() const {
  return _impl_.playercharacter_;
}
inline uint32_t MatchPlayer::playercharacter() const {
  // @@protoc_insertion_point(field_get:HProtocol.MatchPlayer.playerCharacter)
  return _internal_playercharacter();
}
inline void MatchPlayer::_internal_set_playercharacter(uint32_t value) {
  
  _impl_.playercharacter_ = value;
}
inline void MatchPlayer::set_playercharacter(uint32_t value) {
  _internal_set_playercharacter(value);
  // @@protoc_insertion_point(field_set:HProtocol.MatchPlayer.playerCharacter)
}

// -------------------------------------------------------------------

// MatchStart

// uint32 maxPlayer = 2;
inline void MatchStart::clear_maxplayer() {
  _impl_.maxplayer_ = 0u;
}
inline uint32_t MatchStart::_internal_maxplayer() const {
  return _impl_.maxplayer_;
}
inline uint32_t MatchStart::maxplayer() const {
  // @@protoc_insertion_point(field_get:HProtocol.MatchStart.maxPlayer)
  return _internal_maxplayer();
}
inline void MatchStart::_internal_set_maxplayer(uint32_t value) {
  
  _impl_.maxplayer_ = value;
}
inline void MatchStart::set_maxplayer(uint32_t value) {
  _internal_set_maxplayer(value);
  // @@protoc_insertion_point(field_set:HProtocol.MatchStart.maxPlayer)
}

// string killerIP = 3;
inline void MatchStart::clear_killerip() {
  _impl_.killerip_.ClearToEmpty();
}
inline const std::string& MatchStart::killerip() const {
  // @@protoc_insertion_point(field_get:HProtocol.MatchStart.killerIP)
  return _internal_killerip();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MatchStart::set_killerip(ArgT0&& arg0, ArgT... args) {
 
 _impl_.killerip_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:HProtocol.MatchStart.killerIP)
}
inline std::string* MatchStart::mutable_killerip() {
  std::string* _s = _internal_mutable_killerip();
  // @@protoc_insertion_point(field_mutable:HProtocol.MatchStart.killerIP)
  return _s;
}
inline const std::string& MatchStart::_internal_killerip() const {
  return _impl_.killerip_.Get();
}
inline void MatchStart::_internal_set_killerip(const std::string& value) {
  
  _impl_.killerip_.Set(value, GetArenaForAllocation());
}
inline std::string* MatchStart::_internal_mutable_killerip() {
  
  return _impl_.killerip_.Mutable(GetArenaForAllocation());
}
inline std::string* MatchStart::release_killerip() {
  // @@protoc_insertion_point(field_release:HProtocol.MatchStart.killerIP)
  return _impl_.killerip_.Release();
}
inline void MatchStart::set_allocated_killerip(std::string* killerip) {
  if (killerip != nullptr) {
    
  } else {
    
  }
  _impl_.killerip_.SetAllocated(killerip, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.killerip_.IsDefault()) {
    _impl_.killerip_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:HProtocol.MatchStart.killerIP)
}

// uint32 killerCharacter = 4;
inline void MatchStart::clear_killercharacter() {
  _impl_.killercharacter_ = 0u;
}
inline uint32_t MatchStart::_internal_killercharacter() const {
  return _impl_.killercharacter_;
}
inline uint32_t MatchStart::killercharacter() const {
  // @@protoc_insertion_point(field_get:HProtocol.MatchStart.killerCharacter)
  return _internal_killercharacter();
}
inline void MatchStart::_internal_set_killercharacter(uint32_t value) {
  
  _impl_.killercharacter_ = value;
}
inline void MatchStart::set_killercharacter(uint32_t value) {
  _internal_set_killercharacter(value);
  // @@protoc_insertion_point(field_set:HProtocol.MatchStart.killerCharacter)
}

// repeated string survivorIP = 5;
inline int MatchStart::_internal_survivorip_size() const {
  return _impl_.survivorip_.size();
}
inline int MatchStart::survivorip_size() const {
  return _internal_survivorip_size();
}
inline void MatchStart::clear_survivorip() {
  _impl_.survivorip_.Clear();
}
inline std::string* MatchStart::add_survivorip() {
  std::string* _s = _internal_add_survivorip();
  // @@protoc_insertion_point(field_add_mutable:HProtocol.MatchStart.survivorIP)
  return _s;
}
inline const std::string& MatchStart::_internal_survivorip(int index) const {
  return _impl_.survivorip_.Get(index);
}
inline const std::string& MatchStart::survivorip(int index) const {
  // @@protoc_insertion_point(field_get:HProtocol.MatchStart.survivorIP)
  return _internal_survivorip(index);
}
inline std::string* MatchStart::mutable_survivorip(int index) {
  // @@protoc_insertion_point(field_mutable:HProtocol.MatchStart.survivorIP)
  return _impl_.survivorip_.Mutable(index);
}
inline void MatchStart::set_survivorip(int index, const std::string& value) {
  _impl_.survivorip_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:HProtocol.MatchStart.survivorIP)
}
inline void MatchStart::set_survivorip(int index, std::string&& value) {
  _impl_.survivorip_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:HProtocol.MatchStart.survivorIP)
}
inline void MatchStart::set_survivorip(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.survivorip_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:HProtocol.MatchStart.survivorIP)
}
inline void MatchStart::set_survivorip(int index, const char* value, size_t size) {
  _impl_.survivorip_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:HProtocol.MatchStart.survivorIP)
}
inline std::string* MatchStart::_internal_add_survivorip() {
  return _impl_.survivorip_.Add();
}
inline void MatchStart::add_survivorip(const std::string& value) {
  _impl_.survivorip_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:HProtocol.MatchStart.survivorIP)
}
inline void MatchStart::add_survivorip(std::string&& value) {
  _impl_.survivorip_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:HProtocol.MatchStart.survivorIP)
}
inline void MatchStart::add_survivorip(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.survivorip_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:HProtocol.MatchStart.survivorIP)
}
inline void MatchStart::add_survivorip(const char* value, size_t size) {
  _impl_.survivorip_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:HProtocol.MatchStart.survivorIP)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
MatchStart::survivorip() const {
  // @@protoc_insertion_point(field_list:HProtocol.MatchStart.survivorIP)
  return _impl_.survivorip_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
MatchStart::mutable_survivorip() {
  // @@protoc_insertion_point(field_mutable_list:HProtocol.MatchStart.survivorIP)
  return &_impl_.survivorip_;
}

// repeated uint32 survivorCharacter = 6;
inline int MatchStart::_internal_survivorcharacter_size() const {
  return _impl_.survivorcharacter_.size();
}
inline int MatchStart::survivorcharacter_size() const {
  return _internal_survivorcharacter_size();
}
inline void MatchStart::clear_survivorcharacter() {
  _impl_.survivorcharacter_.Clear();
}
inline uint32_t MatchStart::_internal_survivorcharacter(int index) const {
  return _impl_.survivorcharacter_.Get(index);
}
inline uint32_t MatchStart::survivorcharacter(int index) const {
  // @@protoc_insertion_point(field_get:HProtocol.MatchStart.survivorCharacter)
  return _internal_survivorcharacter(index);
}
inline void MatchStart::set_survivorcharacter(int index, uint32_t value) {
  _impl_.survivorcharacter_.Set(index, value);
  // @@protoc_insertion_point(field_set:HProtocol.MatchStart.survivorCharacter)
}
inline void MatchStart::_internal_add_survivorcharacter(uint32_t value) {
  _impl_.survivorcharacter_.Add(value);
}
inline void MatchStart::add_survivorcharacter(uint32_t value) {
  _internal_add_survivorcharacter(value);
  // @@protoc_insertion_point(field_add:HProtocol.MatchStart.survivorCharacter)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
MatchStart::_internal_survivorcharacter() const {
  return _impl_.survivorcharacter_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
MatchStart::survivorcharacter() const {
  // @@protoc_insertion_point(field_list:HProtocol.MatchStart.survivorCharacter)
  return _internal_survivorcharacter();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
MatchStart::_internal_mutable_survivorcharacter() {
  return &_impl_.survivorcharacter_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
MatchStart::mutable_survivorcharacter() {
  // @@protoc_insertion_point(field_mutable_list:HProtocol.MatchStart.survivorCharacter)
  return _internal_mutable_survivorcharacter();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace HProtocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Packet_2eproto
