

#pragma once

#include "NativeGameplayTags.h"

namespace D1GameplayTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Move);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Look);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Run);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Crouch);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Interact);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Parkour);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_TestInput);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Attack1);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Skill1);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_RightClick);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_SpaceBar);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Killer_Attack_DetactStart);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Killer_Attack_DetactEnd);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Killer_Ability_Attack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Killer_Ability_Transform);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Killer_Ability_DamageGenerator);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Killer_Ability_DestroyPallet);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Killer_Ability_PickUpSurvivor);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Killer_Ability_HookSurvivor);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Killer_Ability_VaultWindow);
}