

#pragma once

#include "NativeGameplayTags.h"

namespace D1GameplayTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Move);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Look);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Run);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Crouch);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Interact);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Parkour);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_TestInput);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Attack1);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Skill1);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_RightClick);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_SpaceBar);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Transform_Begin);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Transform_End);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Attack_Begin);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Attack_End);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Attack_DetactStart);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Attack_DetactEnd);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Killer_GeneratorEnd);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Killer_PalletEnd);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Killer_PickUpEnd);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Killer_HookEnd);
}